#!/bin/bash
for i in {3..8}
do
ping 200.100.100.$i -c 1 > /dev/null
errorcode=$?
echo test
if [ $errorcode == 0 ];
then 
echo 200.100.100.$i connected 
else 
echo 200.100.100.$i not connected
fi

done
