#!/bin/bash

for i in {1..5}
do
#run the command ping with a count of 1 and write the output to dev/null 
# dev/null is essentially a null route where we can just dump 
ping 192.168.2.$i -c 1 > /dev/null

#this sets the value of $? to the varible errorcode 
#$?  is a value depending on the outcome of the last command 
#$?  = 0 if the command runs without a problem 
#$? is not 0 if the command has an issue 
errorcode=$?

# if the output of the last command is 0 THEN echo connected 
# else echo not connected 
if [ $errorcode == 0 ];
then
echo "connected to device" 192.168.2.$i
else
echo "not connected to device" 192.168.2.$i
fi
done 

